version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: sh -c 'cd frontend && yarn start'
    ports:
      - "8000:3000"
    tty: true
